In [17]:
import numpy as np

In [18]:
np.__version__

'1.20.1'

In [19]:
a = np.array([1,2,3,4])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
print(a)

[1 2 3 4]


In [22]:
a.dtype

dtype('int32')

In [23]:
a.ndim
# 차원을 알려줌

1

In [24]:
a.shape

(4,)

In [25]:
a.itemsize

4

In [26]:
a.tolist()

[1, 2, 3, 4]

In [27]:
wonbon = np.array([1,2,3])

In [28]:
copy1 = np.array([1,2,3])

In [29]:
wonbon is copy1
# 둘은 값은 서로 같지만 다른존재임

False

In [31]:
copy2 = np.asarray(wonbon)
# asarray 복사는 완전 동일하게 복사함

In [33]:
wonbon is copy2

True

In [35]:
copy3 = wonbon.copy()

In [37]:
wonbon is copy3

True

In [38]:
import pandas as pd

In [39]:
s = pd.Series([1,2,3,4,], index=list('abcd'))

In [40]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [41]:
s.values

array([1, 2, 3, 4], dtype=int64)

In [42]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
s.ndim

1

In [44]:
s.shape

(4,)

In [45]:
s.size

4

In [46]:
s['a']

1

In [47]:
s['d']

4

In [48]:
s['a':'c']
# 값 a부터 값 까지 출력함

a    1
b    2
c    3
dtype: int64

In [50]:
s[:]
# 전부 다 출력함

a    1
b    2
c    3
d    4
dtype: int64

In [52]:
s[:-1]
# 맨 마지막 바로 전값까지만 출력함

a    1
b    2
c    3
dtype: int64

In [53]:
df = pd.DataFrame([[1,2,3,4], [5,6,7,8]], index=list('ab'), columns=list('abcd'))

In [54]:
df

a  b  c  d
a  1  2  3  4
b  5  6  7  8